### ISSUE TITLE
field for mobile and desktop/tablet instruction in the json

### ISSUE THREAD

**Issue by tomallpress** [adaptlearning/adapt-contrib-hotgraphic#74] opened 2014-12-08 12:38 UTC
I've recently put in a request for the narrative to have a field in the json for mobile instruction and one for desktop/tablet (https://github.com/adaptlearning/adapt-contrib-narrative/issues/100). Would it be possible to do a similar thing with the hotgraphic, seens as these two components are so closely linked? I know there is a mobile body field but personally, I don't tend to use that as that implies body text would need to change as well.

I've typically found that it's only ever the instruction that needs to change (because the way the component works changes based on which device you're looking at it on), and the initial text of the component wouldn't need to change as it's just setting the scene for the contents of the component (nothing specific to the device it's being viewed on) .

**Comment by moloko** [comment] 2015-01-06 14:22
closing as duplicate of #56

**Closed by moloko** 2015-01-06 14:22 UTC
Labels: duplicate
